services:
  - type: web
    name: dspfilms-cms
    env: node
    rootDir: ./
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
